# Generated by Django 5.2 on 2025-04-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sign', models.CharField(max_length=20)),
                ('aircraft_type', models.CharField(max_length=20)),
                ('detail', models.CharField(choices=[('fixed_wing', 'Fixed Wing'), ('helicopter', 'Helicopter')], default='fixed_wing', max_length=20)),
                ('origin', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure'), ('enroute', 'Enroute')], default='arrival', max_length=20)),
                ('time', models.TimeField()),
                ('remarks', models.CharField(choices=[('commercial', 'Commercial (Domestic)'), ('private', 'Private'), ('med_evac', 'Med Evac'), ('util/Maint', 'Utility/Maintenance'), ('government', 'Government'), ('military', 'Military')], default='commercial', max_length=30)),
            ],
        ),
    ]
