# Generated by Django 5.2 on 2025-04-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
