# Generated by Django 5.2 on 2025-04-30 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0002_items_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
