# Generated by Django 5.2 on 2025-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0004_items_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='timeliness',
            field=models.CharField(choices=[('commercial', 'Commercial (Domestic)'), ('private', 'Private'), ('med_evac', 'Med Evac'), ('util/Maint', 'Utility/Maintenance'), ('government', 'Government'), ('military', 'Military')], default='on_time', max_length=20),
        ),
    ]
