# Generated by Django 5.2 on 2025-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0006_alter_items_timeliness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='timeliness',
            field=models.CharField(choices=[('delayed', 'Delayed'), ('on_time', 'On Time'), ('N/A', 'N/A (For Enroute)')], default='on_time', max_length=20),
        ),
    ]
