# Generated by Django 5.2 on 2025-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0007_alter_items_timeliness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
