# Generated by Django 5.2 on 2025-05-04 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0008_alter_items_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='action',
            field=models.CharField(choices=[('Arrival', 'Arrival'), ('Departure', 'Departure'), ('Enroute', 'Enroute')], default='arrival', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='detail',
            field=models.CharField(choices=[('Fixed Wing', 'Fixed Wing'), ('helicopter', 'Helicopter')], default='fixed_wing', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='remarks',
            field=models.CharField(choices=[('Commercial', 'Commercial (Domestic)'), ('Private', 'Private'), ('Med_evac', 'Med Evac'), ('Util/Maint', 'Utility/Maintenance'), ('Government', 'Government'), ('Military', 'Military')], default='commercial', max_length=30),
        ),
        migrations.AlterField(
            model_name='items',
            name='timeliness',
            field=models.CharField(choices=[('delayed', 'Delayed'), ('On Time', 'On Time'), ('N/A', 'N/A (For Enroute)')], default='on_time', max_length=20),
        ),
        migrations.AddField(
            model_name='items',
            name='archive_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AirTrafficApp.archivegroup'),
        ),
    ]
