# Generated by Django 5.2 on 2025-05-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0009_archivegroup_alter_items_action_alter_items_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivegroup',
            name='name',
        ),
        migrations.AlterField(
            model_name='items',
            name='detail',
            field=models.CharField(choices=[('Fixed Wing', 'Fixed Wing'), ('Helicopter', 'Helicopter')], default='fixed_wing', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='timeliness',
            field=models.CharField(choices=[('Delayed', 'Delayed'), ('On Time', 'On Time'), ('N/A', 'N/A (For Enroute)')], default='on_time', max_length=20),
        ),
    ]
