# Generated by Django 5.2 on 2025-05-05 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0010_remove_archivegroup_name_alter_items_detail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='action',
            new_name='movement',
        ),
        migrations.AlterField(
            model_name='items',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
