# Generated by Django 5.2 on 2025-05-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0011_rename_action_items_movement_alter_items_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='remarks',
        ),
        migrations.AddField(
            model_name='items',
            name='type_of_flight',
            field=models.CharField(choices=[('Commercial', 'Commercial (Domestic)'), ('GenAv', 'General Aviation'), ('Military', 'Military')], default='commercial', max_length=30),
        ),
    ]
