# Generated by Django 5.2 on 2025-05-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0012_remove_items_remarks_items_type_of_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='movement',
            field=models.CharField(choices=[('Commercial Arrival', 'Commercial Arrival'), ('Commercial Departure', 'Commercial Departure'), ('Commercial Enroute', 'Commercial Enroute'), ('GenAv Arrival', 'GenAv Arrival'), ('GenAv Departure', 'GenAv Departure'), ('GenAv Enroute', 'GenAv Enroute'), ('Military Arrival', 'Military Arrival'), ('Military Departure', 'Military Departure'), ('Military Enroute', 'Military Enroute')], default='arrival', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='timeliness',
            field=models.CharField(choices=[('Commercial Delayed', 'Commercial Delayed'), ('Commercial On Time', 'Commercial On Time'), ('Commercial N/A', 'Commercial N/A'), ('GenAv Delayed', 'GenAv Delayed'), ('GenAv On Time', 'GenAv On Time'), ('GenAv N/A', 'GenAv N/A'), ('Military Delayed', 'Military Delayed'), ('Military On Time', 'Military On Time'), ('Military N/A', 'Military N/A')], default='on_time', max_length=20),
        ),
    ]
