# Generated by Django 5.2 on 2025-05-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0013_alter_items_date_alter_items_movement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='date',
            new_name='date_of_operation',
        ),
    ]
