# Generated by Django 5.2 on 2025-05-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0014_rename_date_items_date_of_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='movement',
            new_name='route_of_flight',
        ),
    ]
