# Generated by Django 5.2 on 2025-05-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0015_rename_movement_items_route_of_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='actual_time',
            field=models.CharField(choices=[('Commercial Delayed', 'Commercial Delayed'), ('Commercial On Time', 'Commercial On Time'), ('Commercial N/A', 'Commercial N/A'), ('GenAv Delayed', 'GenAv Delayed'), ('GenAv On Time', 'GenAv On Time'), ('GenAv N/A', 'GenAv N/A'), ('Military Delayed', 'Military Delayed'), ('Military On Time', 'Military On Time'), ('Military N/A', 'Military N/A')], default='arrival', max_length=20),
        ),
    ]
