# Generated by Django 5.2 on 2025-05-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0016_items_actual_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='time',
        ),
        migrations.AlterField(
            model_name='items',
            name='actual_time',
            field=models.CharField(max_length=20),
        ),
    ]
