# Generated by Django 5.2 on 2025-05-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0017_remove_items_time_alter_items_actual_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='genav_detail',
            field=models.CharField(choices=[('Fixed Wing', 'Fixed Wing'), ('Helicopter', 'Helicopter')], default='fixed_wing', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='actual_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='route_of_flight',
            field=models.CharField(max_length=20),
        ),
    ]
