# Generated by Django 5.2 on 2025-05-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0018_items_genav_detail_alter_items_actual_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='bird_strike',
            field=models.CharField(default='yes', max_length=30),
        ),
        migrations.AlterField(
            model_name='items',
            name='genav_detail',
            field=models.CharField(choices=[('Private', 'Private'), ('Cargo', 'Cargo'), ('Med Evac', 'Med Evac'), ('Utility/Maintenance', 'Utility/Maintenance'), ('Training', 'Training'), ('Government', 'Government')], default='Private', max_length=20),
        ),
    ]
