# Generated by Django 5.2 on 2025-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0019_items_bird_strike_alter_items_genav_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='bird_strike',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
    ]
