# Generated by Django 5.2 on 2025-05-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0020_alter_items_bird_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='runway_incursion',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='yes', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='bird_strike',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='yes', max_length=20),
        ),
    ]
