# Generated by Django 5.2 on 2025-05-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0021_items_runway_incursion_alter_items_bird_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='movement',
            field=models.CharField(choices=[('Arrival', 'Arrival'), ('Departure', 'Departure'), ('Enroute', 'Enroute')], default='Arrival', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='bird_strike',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='runway_incursion',
            field=models.CharField(default='yes', max_length=20),
        ),
    ]
