# Generated by Django 5.2 on 2025-05-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0022_items_movement_alter_items_bird_strike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='bird_strike',
            field=models.CharField(default='yes', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='movement',
            field=models.CharField(choices=[('ARR', 'ARR'), ('DEP', 'DEP')], default='ARR', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='runway_incursion',
            field=models.CharField(default='yes', max_length=50),
        ),
    ]
