# Generated by Django 5.2 on 2025-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0023_alter_items_bird_strike_alter_items_movement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='genav_detail',
            field=models.CharField(choices=[('Private', 'Private'), ('Cargo', 'Cargo'), ('Med Evac', 'Med Evac'), ('Utility/Maintenance', 'Utility/Maintenance'), ('Training', 'Training'), ('Government', 'Government'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='movement',
            field=models.CharField(choices=[('Commercial Arrival', 'Commercial Arrival'), ('Commercial Departure', 'Commercial Departure'), ('Commercial Enroute', 'Commercial Enroute'), ('GenAv Arrival', 'GenAv Arrival'), ('GenAv Departure', 'GenAv Departure'), ('GenAv Enroute', 'GenAv Enroute'), ('Military Arrival', 'Military Arrival'), ('Military Departure', 'Military Departure'), ('Military Enroute', 'Military Enroute')], default='ARR', max_length=20),
        ),
    ]
