# Generated by Django 5.2 on 2025-05-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirTrafficApp', '0024_alter_items_genav_detail_alter_items_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='detail',
            field=models.CharField(choices=[('Fixed Wing', 'Fixed Wing'), ('Helicopter', 'Helicopter')], default='Fixed Wing', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='genav_detail',
            field=models.CharField(choices=[('Arrival Private', 'Arrival Private'), ('Arrival Cargo', 'Arrival Cargo'), ('Arrival Med Evac', 'Arrival Med Evac'), ('Arrival Utility/Maintenance', 'Arrival Utility/Maintenance'), ('Arrival Training', 'Arrival Training'), ('Arrival Government', 'Arrival Government'), ('Departure Private', 'Departure Private'), ('Departure Cargo', 'Departure Cargo'), ('Departure Med Evac', 'Departure Med Evac'), ('Departure Utility/Maintenance', 'Departure Utility/Maintenance'), ('Departure Training', 'Departure Training'), ('Departure Government', 'Departure Government'), ('Enroute Private', 'Enroute Private'), ('Enroute Cargo', 'Enroute Cargo'), ('Enroute Med Evac', 'Enroute Med Evac'), ('Enroute Utility/Maintenance', 'Enroute Utility/Maintenance'), ('Enroute Training', 'Enroute Training'), ('Enroute Government', 'Enroute Government')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='movement',
            field=models.CharField(choices=[('Arrival', 'Arrival'), ('Enroute', 'Enroute'), ('Departure', 'Departure')], default='Arrival', max_length=20),
        ),
    ]
